api = "0.5"

[buildpack]
  id = "making/opentelemetry-javaagent"
  version = "0.1.7"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "*"

[metadata]
  [[metadata.dependencies]]
    id = "opentelemetry-javaagent"
    name = "OpenTelemetry Java Agent"
    sha256 = "93e0d115d30117f84282630f73b897b5fd94d76e59f26da934ce9e6ee6d11499"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
    uri = "https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.14.0/opentelemetry-javaagent.jar"
    version = "1.14.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/open-telemetry/opentelemetry-java-instrumentation/raw/main/LICENSE"
