api = "0.5"

[buildpack]
  id = "making/opentelemetry-javaagent"
  version = "0.1.5"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "*"

[metadata]
  [[metadata.dependencies]]
    id = "opentelemetry-javaagent"
    name = "OpenTelemetry Java Agent"
    sha256 = "3cd76a1f45f4654072d6b929c7802bca1401f7113e37666ea9a4bc15871a01d6"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
    uri = "https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.12.1/opentelemetry-javaagent.jar"
    version = "1.12.1"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/open-telemetry/opentelemetry-java-instrumentation/raw/main/LICENSE"
