name: Release
on:
  release:
    types:
    - published
jobs:
  register:
    name: Package, Publish, and Register
    runs-on:
    - ubuntu-latest
    steps:
    - id: checkout
      uses: actions/checkout@v2
    - if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - id: setup-pack
      uses: buildpacks/github-actions/setup-pack@v4.1.0
    - id: package
      run: |
        #!/usr/bin/env bash
        set -exuo pipefail
        BP_ID="$(cat buildpack.toml | yj -t | jq -r .buildpack.id)"
        VERSION="$(cat buildpack.toml | yj -t | jq -r .buildpack.version)"
        PACKAGE="${DOCKER_REGISTRY}/${DOCKER_USERNAME}/buildpacks/$(echo ${BP_ID} | awk -F '/' '{print $2}')"
        ./bin/vendor-assets
        pack buildpack package --publish ${PACKAGE}:${VERSION}
        pack buildpack package --publish ${PACKAGE}:latest
        DIGEST="$(crane digest ${PACKAGE}:${VERSION})"
        echo "::set-output name=bp_id::${BP_ID}"
        echo "::set-output name=version::${VERSION}"
        echo "::set-output name=address::${PACKAGE}@${DIGEST}"      
      shell: bash
      env:
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}